# Predict Metallic Glass Properties

In [1]:
import pandas as pd
from foundry import Foundry
from garden_ai import GardenClient

# Set DOIs for the dataset and model to use. 
# You can find these in the Web UIs
metallic_glass_dataset = "10.18126/7yg1-osf2"
metallic_glass_model = "10.26311/ep98-br79"

#Instantiate clients for Foundry-ML and Garden
f = Foundry()
g = GardenClient()

# Fetch the data from MDF/Foundry-ML
ds = f.get_dataset(doi=metallic_glass_dataset)
X,y = ds.load()['train']
comp_list = [c for c in X.iloc[0:100].Composition]

# Run the model with Garden-AI
garden = g.get_published_garden(metallic_glass_model)
result = garden.predict_metallicglass_Rc_LLM(comp_list)
result

Output()

WARNING: Local SDK and remote worker execution environment differences detected for endpoint 6ed5d749-abc3-4c83-bcad-80837b3d126f -
  SDK uses Python 3.12.4/Dill 0.3.6 but worker used 3.11.8/0.3.6
  (worker SDK version: 2.25.0; worker OS: Linux-5.14.0-427.18.1.el9_4.x86_64-x86_64-with-glibc2.36)
Dill and Python version mismatches can cause issues during function/argument (de)serialization. Globus Compute recommends keeping them in sync.

,Compositions,Predicted log Rc (K/s),Ebar log Rc (K/s),d_pred,rmse/std_y Domain Prediction from Max F1,cdf_area Domain Prediction from Max F1
0,Ag0.09 Al8.69 Cu39.07 Zr52.15,0.714183,1.110035,0.112070,ID,OD
1,Ag0.3 B4 Cu1.5 P18 Pt74.7 Si1.5,2.607334,2.505214,1.000000,OD,OD
2,Ag1 Al19.8 Co19.8 Cu4.95 Zr54.45,1.438236,1.349331,0.093473,ID,OD
3,Ag1 Al7 Cu49 Zr43,0.964992,1.452317,0.070655,ID,OD
4,Ag1 Al9.9 Cu22.77 Fe4.95 Zr61.38,1.195685,1.131523,0.162742,ID,OD
...,...,...,...,...,...,...
95,Ag20 Cu40 Ti10 Zr30,0.932368,1.717024,0.370204,ID,OD
96,Ag20 Cu40 Zr40,0.832473,2.029364,0.385801,ID,OD
97,Ag20 Cu5 Gd10 Mg65,1.209847,1.680807,1.000000,OD,OD
98,Ag21 Cu42 Fe37,6.692762,5.922453,0.908296,ID,OD
99,Ag22 Cu41 Fe37,6.692046,5.923927,0.908306,ID,OD

# Predict Hardness of High Entropy Alloys by Composition

In [2]:
import pandas as pd
from foundry import Foundry
from garden_ai import GardenClient

# Set DOIs for the dataset and model to use. 
# You can find these in the Web UIs
hea_dataset = "10.18126/rska-ta67"
hea_model = "10.26311/ep98-br79"

#Instantiate clients for Foundry-ML and Garden
f = Foundry(use_globus=False)
g = GardenClient()

# Fetch the data from MDF/Foundry-ML
ds = f.get_dataset(doi=hea_dataset)
X,y = ds.load()['train']
comp_list = [c for c in X.iloc[0:100].Composition]

# Run the model with Garden-AI
garden = g.get_published_garden(hea_model)
result = garden.predict_hea_hardness(comp_list)
result

Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/Foundry_dataset_upload_hea_hardness.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/hea_hardness_Yang_ActaMat2022.xlsx
Downloading... 0.03 MBError downloading file: 404 Client Error: Not Found for url: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/.ipynb_checkpoints/1.1/.ipynb_checkpoints/Foundry_dataset_upload_hea_hardness-checkpoint.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/Foundry_dataset_upload_hea_hardness.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/hea_hardness_Yang_ActaMat2022.xlsx
Downloading... 0.03 MBError downloading file: 404 Client Error: Not Found for url: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/.ipynb_checkpoints/1.0/.ipynb_checkpoints/Foundry_dataset_upload_hea_hardness-checkpoint.ipynb
Loading from version folder: 1.1

Output()

,Compositions,Predicted HEA hardness (HV),Ebar HEA hardness (HV),d_pred,rmse/std_y Domain Prediction from Max F1,cdf_area Domain Prediction from Max F1
0,Co22.2Cr22.2Fe22.2Ni22.2Mo11.1,305.379867,144.593831,1.000000,OD,OD
1,Al10Co20Cr20Fe20Ni20Mo10,485.845467,109.651044,0.922615,ID,OD
2,Al20Co10Cr20Fe20Ni20Mo10,766.510467,58.967527,0.747353,ID,OD
3,Al20Co20Cr20Fe10Ni20Mo10,750.138400,38.312351,0.762642,ID,OD
4,Al19.6Co19.6Cr19.6Fe11.8Ni19.6Mo9.8,750.929200,28.940233,0.735282,ID,OD
...,...,...,...,...,...,...
95,Co22.5Cr22.5Cu22.5Fe22.5Ni10,165.903533,33.122552,1.000000,OD,OD
96,Co21.3Cr21.3Cu21.3Fe21.3Ni15,165.508667,15.209133,1.000000,OD,OD
97,Co16.7Cr16.7Cu16.7Fe16.7Ni33.3,159.582000,24.406236,1.000000,OD,OD
98,Co26.7Cr26.7Fe26.7Ni20,150.952000,61.383962,1.000000,OD,OD
99,Co20Cr20Fe20Ni40,135.248000,25.379747,1.000000,OD,OD

In [3]:
garden

PublishedGarden(title='Garden of assorted materials properties', authors=['Ryan Jacobs'], contributors=[], doi='10.26311/ep98-br79', description='Garden containing random forest models of 33 materials properties to provide predictions, error bars, and domain of applicability guidance', publisher='Garden-AI', year='2024', language='en', tags=[], version='0.0.1', entrypoints=[RegisteredEntrypoint(doi='10.26311/3p8f-se33', title='Bandgap model', authors=['Ryan Jacobs'], short_name='predict_bandgap', description='Random forest model to predict the electronic bandgap of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_bandgap', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('aff94a0f-4417-4c01-b2ab-76f1a26b55c8'), container_uuid=UUID('d2deb27a-a67c-4772-b986-c141db43a14e'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-090914010323', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/bandgap_notebook.ipynb-568788e62819ab82bbd0df90c3a7382469f71490966c6c0faa1689a2b306b3d8.ipynb', steps=[], test_functions=["@entrypoint_test(predict_bandgap)\ndef test_the_model():\n    example_input = ['SiO2', 'SrTiO3', 'Al2O3']\n    result = predict_bandgap(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/fq14-0d14', title='Concrete model', authors=['Ryan Jacobs'], short_name='predict_concrete', description='Random forest model to predict the compressive strength of concrete mixtures', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_concrete', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('d84c6380-547d-4e21-b0a1-225dd2a130a7'), container_uuid=UUID('ef10a688-eb34-46e5-963e-ccaf4995b237'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-105306926638', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/concrete_notebook.ipynb-d016dbe83dd8ec2b0a0d82146466234dfd83a0ef2b546ab916e13879782c7065.ipynb', steps=[], test_functions=["@entrypoint_test(predict_concrete)\ndef test_the_model():\n    import pandas as pd\n    d_test = {'Cement (component 1)(kg in a m^3 mixture)' : [540, 540],\n              'Blast Furnace Slag (component 2)(kg in a m^3 mixture)': [0, 0],\n              'Fly Ash (component 3)(kg in a m^3 mixture)': [0, 0],\n              'Water  (component 4)(kg in a m^3 mixture)': [162, 162],\n              'Superplasticizer (component 5)(kg in a m^3 mixture)': [2.5, 2.5],\n              'Coarse Aggregate  (component 6)(kg in a m^3 mixture)': [1040, 1055],\n              'Fine Aggregate (component 7)(kg in a m^3 mixture)': [676, 676],\n              'Age (day)': [28, 28]}\n    \n    result = predict_concrete(pd.DataFrame(d_test))\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/ne10-cw51', title='Piezoelectric displacement model', authors=['Ryan Jacobs'], short_name='predict_piezoelectric', description='Random forest model to predict max piezoelectric displacement of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_piezoelectric', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('268771cf-b89e-4c14-bc7f-1f3ef79e3f09'), container_uuid=UUID('f0e316ef-3abb-454d-836a-7f009c19dc15'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-114833860918', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/piezoelectric_notebook.ipynb-c3690129d4adec9d75dbc058189e71559da8b36cbc54fd65a46215311f01354e.ipynb', steps=[], test_functions=["@entrypoint_test(predict_piezoelectric)\ndef test_the_model():\n    example_input = ['AgI', 'CdTe', 'BN']\n    result = predict_piezoelectric(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/xc43-an24', title='Dielectric constant model', authors=['Ryan Jacobs'], short_name='predict_dielectric', description='Random forest model to predict the dielectric constant of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_dielectric', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('39b0883d-625c-4231-8420-aea2bd035512'), container_uuid=UUID('85efa994-f043-4ddc-bd31-dfc0138771d9'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-122700087830', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/dielectric_notebook.ipynb-b32900dcb8d51654d7fc6e964470b117c88fb555bd5940d3c778486b1543abd6.ipynb', steps=[], test_functions=["@entrypoint_test(predict_dielectric)\ndef test_the_model():\n    example_input = ['Rb2Te', 'CdCl2', 'MnI2']\n    result = predict_dielectric(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/da1c-y367', title='Dilute solute diffusion model', authors=['Ryan Jacobs'], short_name='predict_diffusion', description='Random forest model to predict the dilute solute activation energy for diffusion', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_diffusion', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('eef61f80-e765-4716-bb92-bb0750f50e4d'), container_uuid=UUID('a8d9f8c2-9bc8-4494-a75c-575f53d6e2c2'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-123719834232', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/diffusion_notebook.ipynb-b03f31049dc27837edf2091079b72d104a39c654c5bd69e685f64c9955733c18.ipynb', steps=[], test_functions=["@entrypoint_test(predict_diffusion)\ndef test_the_model():\n    example_input = ['AgAg', 'AgCo', 'AgCr']\n    result = predict_diffusion(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/1bgd-3w38', title='Double perovskite bandgap model', authors=['Ryan Jacobs'], short_name='predict_double_perovskite_gap', description='Random forest model to predict the bandgap of double perovskites', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_double_perovskite_gap', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('3801c6da-0b7a-4900-bb38-a7ff1c6454cc'), container_uuid=UUID('a4fcebd9-d330-4db4-956b-071103017bd7'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-124347440580', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/double_perovskite_gap_notebook.ipynb-ce9336267ae6885c519e90409f5eac4e2b23902ff92eecf10469bfe66480991a.ipynb', steps=[], test_functions=["@entrypoint_test(predict_double_perovskite_gap)\ndef test_the_model():\n    example_input = ['AgNbLaAlO6', 'AgNbLaGaO6', 'AgNbLaInO6']\n    result = predict_double_perovskite_gap(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/hh7f-ar11', title='Elastic tensor model', authors=['Ryan Jacobs'], short_name='predict_elastic_tensor', description='Random forest model to predict the bulk modulus of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_elastic_tensor', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('be7ba8af-527e-42ae-b97e-ff23521c0a2e'), container_uuid=UUID('6253e92e-1ed2-4f43-85b2-ce15545cf572'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-125534891248', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/elastic_tensor_notebook.ipynb-bf3c2c94be4de9b40ae5f76b4383e0db6c91482c2c4a574a6b5e30241186a40c.ipynb', steps=[], test_functions=["@entrypoint_test(predict_elastic_tensor)\ndef test_the_model():\n    example_input = ['Nb4CoSi', 'Al(CoSi)2', 'SiOs']\n    result = predict_elastic_tensor(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/byhv-bh08', title='Exfoliation energy model', authors=['Ryan Jacobs'], short_name='predict_exfoliationE', description='Random forest model to predict the exfoliation energy of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_exfoliationE', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('088aca36-78dc-4b5a-9b5c-c8ea84a047f6'), container_uuid=UUID('c59d1a4f-d303-4c3b-a50f-b466b657bd6f'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-130216496150', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/exfoliationE_notebook.ipynb-9fae6b6a917df5fdd2ec80fcd3b93435933c63d118de9d8e5f9b1c0b32642269.ipynb', steps=[], test_functions=["@entrypoint_test(predict_exfoliationE)\ndef test_the_model():\n    example_input = ['HfSiTe', 'As', 'TiOBr']\n    result = predict_exfoliationE(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/e9rx-7020', title='High entropy hardness model', authors=['Ryan Jacobs'], short_name='predict_hea_hardness', description='Random forest model to predict the hardness of high entropy alloys', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_hea_hardness', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('f844b1bf-9f1b-4d66-af1a-416e04cf72d3'), container_uuid=UUID('f44d8972-1506-4e97-a685-4287a92a5b16'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-130848357704', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/hea_hardness_notebook.ipynb-ce26cd4175a70d75d35174bbbde8782a893c73ec5e5870e519360bdb9c128b57.ipynb', steps=[], test_functions=["@entrypoint_test(predict_hea_hardness)\ndef test_the_model():\n    example_input = ['Co22.2Cr22.2Fe22.2Ni22.2Mo11.1', 'Al10Co20Cr20Fe20Ni20Mo10', 'Al20Co10Cr20Fe20Ni20Mo10']\n    result = predict_hea_hardness(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/9fan-dk80', title='Heusler magnetization model', authors=['Ryan Jacobs'], short_name='predict_heusler', description='Random forest model to predict the magnetization of Heusler alloys', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_heusler', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('77451a50-8399-4698-9ae4-54478029c0a5'), container_uuid=UUID('b2aacdbe-4462-4fa4-a121-a142b3a06663'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-144751188394', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/heusler_notebook.ipynb-90e3ffe60b1ce651ff9514c6c8e89fec09f1a788b996b41ef57bc20fcc1ebfed.ipynb', steps=[], test_functions=["@entrypoint_test(predict_heusler)\ndef test_the_model():\n    comps_list = ['V2ScAl', 'V2ScGa', 'V2ScIn']\n    numelec_list = [16, 16, 16]\n    heuslertype_list = ['Full Heusler', 'Full Heusler', 'Full Heusler']\n    result = predict_heusler(comps_list, numelec_list, heuslertype_list)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/mk1a-ve41', title='Lithium solid state electrolyte conductivity model', authors=['Ryan Jacobs'], short_name='predict_Li_conductivity', description='Random forest model to predict the conductivity of Li in solid electrolytes', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_Li_conductivity', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('d55061d5-62ef-4654-a749-7f0e7089e6a2'), container_uuid=UUID('e3b340e6-17ca-424e-b159-581f74bb75c2'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-145917015604', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/Li_conductivity_notebook.ipynb-3b6560684887f18e4e884e4d2bcf2cfa947a6d46e5bf9d4e2493f7fb72a0a6a9.ipynb', steps=[], test_functions=["@entrypoint_test(predict_Li_conductivity)\ndef test_the_model():\n    example_input = ['Li2OHBr', 'Li2.4OH0.6Cl', 'Li2.1OH0.9Cl']\n    result = predict_Li_conductivity(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/vtx9-dq38', title='Metallic glass Dmax model', authors=['Ryan Jacobs'], short_name='predict_metallicglass_Dmax', description='Random forest model to predict the maximum casting diameter of metallic glasses', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_metallicglass_Dmax', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('f213e6ed-61ec-4a8f-8066-4dda88db749b'), container_uuid=UUID('c0e92c07-d9e6-4a85-9989-42923d12769a'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-153045804699', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/metallicglass_Dmax_notebook.ipynb-e31e17227cb8d36be37de481c3f3ca5b87ab2458442f83b707bba2fd8076bd15.ipynb', steps=[], test_functions=["@entrypoint_test(predict_metallicglass_Dmax)\ndef test_the_model():\n    example_input = ['Ag1Al19.8Co19.8Cu4.95Zr54.45', 'Ag1Al9.9Cu22.77Fe4.95Zr61.38', 'Ag1Cu5P5Pd79Si10']\n    result = predict_metallicglass_Dmax(example_input)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/q8w2-gh81', title='Metallic glass Rc model', authors=['Ryan Jacobs'], short_name='predict_metallicglass_Rc', description='Random forest model to predict the critical cooling rate of metallic glasses', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_metallicglass_Rc', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('a7cd20e1-926b-4b8c-9b56-a7d2f4005239'), container_uuid=UUID('f7e45b48-b678-4181-8d6e-f64219fc382d'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-154951273656', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/metallicglass_Rc_notebook.ipynb-408d06d3ca597170a57a6a2b86ee440cce8787f655e0f883a17e22a5af29f39c.ipynb', steps=[], test_functions=["@entrypoint_test(predict_metallicglass_Rc)\ndef test_the_model():\n    comps_list = ['Zr66Al8Ni26', 'Zr66Al8Cu7Ni19', 'Zr66Al8Cu12Ni14']\n    datatype_list = ['expt', 'expt', 'expt']\n    result = predict_metallicglass_Rc(comps_list, datatype_list)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/17nn-hj98', title='Metallic glass Rc model (LLM data)', authors=['Ryan Jacobs'], short_name='predict_metallicglass_Rc_LLM', description='Random forest model to predict the critical cooling rate of metallic glasses (data from LLMs)', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_metallicglass_Rc_LLM', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('39118812-c74a-4679-854f-947a56c0557f'), container_uuid=UUID('45eb40f9-3123-45c1-9969-d6886839afdf'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240329-155715047541', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/metallicglass_Rc_LLM_notebook.ipynb-6b1a924379f3173cf16e9a1c8307cbca5e1d7c0e9f21d0c8eeb76c6771752b8c.ipynb', steps=[], test_functions=["@entrypoint_test(predict_metallicglass_Rc_LLM)\ndef test_the_model():\n    comps_list = ['Cu30Ni10P20Pd40', 'Cu0.5Zr0.5','Ni40P20Pd40']\n    result = predict_metallicglass_Rc_LLM(comps_list)\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/mdqx-tv62', title='Magnesium alloy yield strength model', authors=['Ryan Jacobs'], short_name='predict_Mg_alloy', description='Random forest model to predict the yield strength of Mg alloys', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_Mg_alloy', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('e8a3f792-23e8-4134-b12b-41d92bc18868'), container_uuid=UUID('06fead17-bebd-4f62-bc33-21f7172c1105'), base_image_uri='gardenai/base:python-3.11-wisconsin', full_image_uri='public.ecr.aws/x2v7f8j4/garden-containers-prod:pushed-20240401-092127335366', notebook_url='https://pipeline-notebooks-prod.s3.amazonaws.com/RJACOBS3@WISC.EDU/Mg_alloy_notebook.ipynb-d34c5934943cd421234130c33cc3ebc398bba4e39d21663e32be4eda54ec997c.ipynb', steps=[], test_functions=["@entrypoint_test(predict_Mg_alloy)\ndef test_the_model():\n    import pandas as pd\n    d_test = {'Mg(wt.%)' : [99.27, 98.77],\n              'Zn(wt.%)': [0, 0],\n              'Y(wt.%)': [0.73, 1.23],\n              'Zr(wt.%)': [0, 0],\n              'Nd(wt.%)': [0, 0],\n              'Gd(wt.%)': [0, 0],\n              'solution temperature(°Ê)': [525, 525],\n              'solution time(h)': [7, 7],\n             'homogenization temperature(°Ê)': [0, 0],\n             'homogenization time(h)': [0, 0],\n             'extrusion temperature(°Ê)': [0, 0],\n             'extrusion ratio': [],\n             'aging temperature(°Ê)': [],\n             'aging time(h)': []}\n    \n    result = predict_Mg_alloy(pd.DataFrame(d_test))\n    return result\n"], requirements=[]), RegisteredEntrypoint(doi='10.26311/fjcs-0827', title='Thermal conductivity model of materials', authors=['Ryan Jacobs'], short_name='predict_thermal_conductivity', description='Random forest model to predict the thermal conductivity of materials', year='2024', tags=['scikit-learn', 'mastml'], models=[ModelMetadata(model_identifier='https://github.com/uw-cmg/model_thermal_conductivity', model_repository='GitHub', model_version='main', datasets=[])], repositories=[], papers=[], datasets=[], doi_is_draft=True, func_uuid=UUID('d9c0a44d-d512-4038-9b0b-871e0ca0aee1'

In [4]:
import pandas as pd
from foundry import Foundry
from garden_ai import GardenClient

# Set DOIs for the dataset and model to use. 
# You can find these in the Web UIs
tc_dataset = "10.18126/xlfr-hjrn"
tc_model = "10.26311/ep98-br79"

#Instantiate clients for Foundry-ML and Garden
f = Foundry(use_globus=False)
g = GardenClient()

# Fetch the data from MDF/Foundry-ML
ds = f.get_dataset(doi=hea_dataset)
X,y = ds.load()['train']
comp_list = [c for c in X.iloc[0:100].Composition]

# Run the model with Garden-AI
garden = g.get_published_garden(tc_model)
result = garden.predict_superconductivity(comp_list)
result

Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/Foundry_dataset_upload_hea_hardness.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/hea_hardness_Yang_ActaMat2022.xlsx
Downloading... 0.03 MBError downloading file: 404 Client Error: Not Found for url: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.1/.ipynb_checkpoints/1.1/.ipynb_checkpoints/Foundry_dataset_upload_hea_hardness-checkpoint.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/Foundry_dataset_upload_hea_hardness.ipynb
Starting Download of: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/hea_hardness_Yang_ActaMat2022.xlsx
Downloading... 0.04 MBError downloading file: 404 Client Error: Not Found for url: https://data.materialsdatafacility.org/foundry/Dataset_hea_hardness/1.0/.ipynb_checkpoints/1.0/.ipynb_checkpoints/Foundry_dataset_upload_hea_hardness-checkpoint.ipynb
Loading from version folder: 1.1

Output()

,Compositions,Predicted ln Tc (K),Ebar ln Tc (K),d_pred,rmse/std_y Domain Prediction from Max F1,cdf_area Domain Prediction from Max F1
0,Co22.2Cr22.2Fe22.2Ni22.2Mo11.1,2.494058,0.162730,1.0,ID,OD
1,Al10Co20Cr20Fe20Ni20Mo10,2.469098,0.166878,1.0,ID,OD
2,Al20Co10Cr20Fe20Ni20Mo10,2.482940,0.176342,1.0,ID,OD
3,Al20Co20Cr20Fe10Ni20Mo10,2.491401,0.178062,1.0,ID,OD
4,Al19.6Co19.6Cr19.6Fe11.8Ni19.6Mo9.8,2.494351,0.182716,1.0,ID,OD
...,...,...,...,...,...,...
95,Co22.5Cr22.5Cu22.5Fe22.5Ni10,2.492046,0.178061,1.0,ID,OD
96,Co21.3Cr21.3Cu21.3Fe21.3Ni15,2.495564,0.178677,1.0,ID,OD
97,Co16.7Cr16.7Cu16.7Fe16.7Ni33.3,2.543672,0.215451,1.0,ID,OD
98,Co26.7Cr26.7Fe26.7Ni20,2.476485,0.160318,1.0,ID,OD
99,Co20Cr20Fe20Ni40,2.498149,0.175988,1.0,ID,OD